spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    username: postgres
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/customer
    password: gremio83
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    format_sql: 'true'
#    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
